### ISSUE TITLE
Implement a password manager for GLAP

### ISSUE THREAD

**Issue by davipirata** [calpirateparty/GLAP#3]
Find a solution for storing the keys

**Comment by 2041876935** [comment]
How do I prioritize this Issue?

**Comment by 2041876935** [comment]
Okay, so what are your leading potential solutions? Not sure I fully comprehend IPFS... 

SeaFile looks interesting, and SparkleShare...

**Comment by davipirata** [comment]
IPFS sounds interesting, but I was thinking more in lines with LastPass:
https://opensource.com/article/16/12/password-managers

**Comment by sptankard** [comment]
So, I would softly oppose LastPass on two grounds: 
1) it's proprietary 
2) security

https://arstechnica.com/security/2015/06/hack-of-cloud-based-lastpass-exposes-encrypted-master-passwords/
https://blog.lastpass.com/2016/09/time-to-change-every-password.html/

**Comment by sptankard** [comment]
@davipirata from the link you posted, there's a couple programs that I'm not familiar with and which look interesting:
https://padlock.io/
https://www.passbolt.com/

...maybe should look into them.

IPFS: I don't think IPFS is what we need, just mentioned it offhand before because it's a cool piece of tech. Not what we need though.

**Comment by sptankard** [comment]
Cross-posting (copy-paste) from the RocketChat to here (N.B. context was we had already settled on KeePassXC and were looking for a sync solution)...
https://chat.calpirateparty.org/channel/infosec_policy

So after a fair bit of research, I'd like to tentatively propose the following set of software as our credential/password/logon sharing solution:
https://keepassxc.org
https://addons.mozilla.org/en-us/firefox/addon/passifox
https://chrome.google.com/webstore/detail/chromeipass/ompiailgknfdndiefoaoiligalphfdae
    chromeIPass
    KeePass integration for browser Chrome using KeePassHttp
https://storj.io
    Storj - Decentralized Cloud Storage
    Distributed, encrypted, and blazing fast object storage, where only you have access to your data.

Storj would be a solution for storing/syncing the KeePass db files, distributing access to those who need it.

[...]

About credential db syncing mechanisms, i do think it's rather necessary. From my survey of systems we're down to syncthing, storj, and maybe sparkleshare
Maybe git-annex
N.b. since we're using keepassdbs with brute-force-resistant passwords, the trust we need to place in the syncing solution is relatively low. (It's just a dumb truck/box.)
The syncing mechanism is about convenience and rapidity, which will affect security and general productivity/ease of use.
List of syncing solutions i've surveyed so far
Storj
Git-annex
Syncthing? Maybe. Stable/mature? Android app hard freezes the phone.
Sparkleshare
Syncany? Unmaintained
Spideroak? Unmaintained
Peerwasp? Unmaintained
Dropbox? Proprietary
Tahoe-lafs? Could self-host 😕
Tahoe w LeastAuthority's S4? Expensive.
IPFS? Maybe. Privacy/e2e encryption?
Google drive? Proprietary

@zarathustra browser extensions *are* a weak link, however: i think the convenience they provide will lead to security benefits that outweigh the security negatives of their implementation. For example, without using them, ppl will have to manually copy-paste passwds from keepassXC. Even the most careful person is likely to sometimes paste these into a google search box, or worse, some random etherpad. Less careful ppl may invent their own custom schemes for keeping track of their passwds that are even worse. 

Whatever sync solution we use, we can keep the keepass files in a git repo for versioning. (Git-annex for binary handling.)

Also n.b. there exist packages like [Hashicorp Vault](https://www.vaultproject.io/), but these are much more heavy duty than we need.

**Comment by davipirata** [comment]
This task is ill defined I think. Let's change the name for:
Implement a password manager for GLAP
and I would go ahead and assign @sptankard to find and implement something for us... two :+1: and I update the issue :)
@calpirateparty/capp-it what do you think?

**Comment by 2041876935** [comment]
Long-term we still need a solution for this.

But short-term, I've begrudgingly created a LastPass account. Handing over to @sptankard now.

**Comment by sptankard** [comment]
Aye, we have the LastPass for now, pending a viable FLOSS solution at some point. Closing.
